### ISSUE TITLE
Unbunching using IPT2

### ISSUE THREAD

**Issue by helloiamson** [Vectorial1024/ExpressBusServices_IPT2#1]
Hi,

Thank you very much for the mod and it certainly unlocks the potential of buses in the C:S.

I personally prefer IPT2 over TLM because it allow me to configure where unbunching should occur, most usually at terminus. Unless a route is looped, I would allow unbunching to occur at the two ends of the route, like in real life.

Therefore, I wonder if you can please add a feature to only allow "stop-on-demand" at stops where "vehicle unbunching" is FALSE as defined using IPT2, and to disallow "stop-on-demand" at stops where "vehicle unbunching" is TRUE. In this case, unbunching do not necessarily need to occur at the first stop.

I look forward to seeing this feature in the upcoming update.

Thanks,
Herman

**Comment by Vectorial1024** [comment]
OK, it is done! https://steamcommunity.com/sharedfiles/filedetails/?id=2296003260

For correctness you may want to begin the transition by picking "Respect IPT2 unbunching", but for convenience and to have less mouse clicks in general later on, you could eventually transition to "Invert IPT2 unbunching" where you only need to disable the toggle at the termini stops and watch this mod unbunch buses right at those termini and not at intermediate stops.

**Comment by helloiamson** [comment]
Thank you very much for the brilliant work. Works like a charm!
