### ISSUE TITLE
Invert IPT2 unbunching doesnt seem to work

### ISSUE THREAD

**Issue by CrankyAnt** [Vectorial1024/ExpressBusServices_IPT2#2]
Hi,

Recently had to switch back to IPT2 because TLM unfortunately doesnt have correct earnings from PT.. so Im using your mod now to sort of mimic the Express function TLM has built-in. Thanks for making this mod!

Now my problem is that I wanted to use "Invert IPT2 unbunching" so that I can only let them unbunch at termini and start. However it seems that it inverts the order of unbunching/boarding which results in not unbunching at those stops at all. When I switch to "first principle" all is working fine at startpoint.. but this mode is not optimal since I also want the busses to unbunch at the endpoints (designated stops where I turned off unbunching in IPT2).

On your steamworkshop page I saw some comments about similar problems but that was related to a problem after a system shutdown, thats not the case for me as it just never works. 

Hope you can help or shed some light on the issue :D Thanks!

**Comment by Vectorial1024** [comment]
Hi there! Thanks for using the mod!

You may look at #1 (the three options mentioned there are implemented now), but to summarize, "First Principles" simply brings you the exact same feature of the base mod (EBS), which (if I remember correctly) overrides IPT2's unbunching control.

From what you are describing, perhaps you could choose "Respect IPT2", see if it helps.

The bottom line is that you should standardize how the unbunching should be represented across all your bus lines. If you decide to use eg "Invert IPT2" then every bus line WILL use "Invert IPT2". This is for simplicity of this mod and also helps you avoid confusing config errors.

**Comment by CrankyAnt** [comment]
Yes, first principle indeed overrides IPT2's unbunching and does it only at the first stop, which works great. 
My problem however is that I also want to unbuch somewhere midline, usually this is the place the route leads to, before it turns around and goes back to the startpoint. 
A simple example: Start --> stop#2--> stop#3 --> Termini --> stop#5 (#3) --> stop#6 (# 2) --> Start

In this example I would like to unbunch at "Start" and "Termini", all other stops there is no unbunching happening. Following the steps in your guide I have set unbunching off at "Start" and "Termini" stops and used the "Invert IPT2" option. This way it should unbunch at those 2 stops and leave the rest alone. 

However what I do observe is that when a bus arrives at "Start" or "Termini" it unbunchess for a microsecond and then it start loading, after that it just drives off. Normal unbunching behaviour is to first load passengers and then unbunch for a certain amount of time. 

So my original issue is not about understanding these methods but because I think the unbunch/loading order actually get reversed when using this policy. When I use the first principle policy it uses the right order (load and then unbunch) but ofc only at the first stop like it should do. 

Hope this time I have been able to explain the issue in a better way, let me know when its not entirely clear. 

Thanks!

**Comment by PlAn-K** [comment]
Also here. I'm using Invert IPT Unbunching option in this mod, but It doesn't work well.

I unselected the 'Unbunching' option in the specific station, but the bus didn't unbunch at one. Option 1(Base mod option) is perfectly working, and I also checked that Option 2 is working.

**Comment by Vectorial1024** [comment]
Hi all, an update after many time

It seems to be related to a recent issue discovered in the main mod https://github.com/Vectorial1024/ExpressBusServices/issues/14 and so for further info, you may read the issue page on the other side. But the main idea is, the terminus detection logic in the base mod may be incorrect, therefore causing e.g. this mod to seemingly behave strangely.

**Comment by Vectorial1024** [comment]
The bug related to wrong unbunching locations have been fixed at Steam.

It seems that there are actually 2 bugs being reported in this issue page. To avoid confusion, if there are anything to follow up after this, please create a new issue.

Closing this.
