### ISSUE TITLE
Aggressive Mode Skip-Stop Behaviour in Conjunction with IPT2

### ISSUE THREAD

**Issue by helloiamson** [Vectorial1024/ExpressBusServices_IPT2#3]
Hi,
Thanks for adapting the TLM skip-stop behaviour in the main mod. It is working very nicely as intended.

I would like to report 2 situations occuring when the agressive mode is used in conjunction with IPT2.
1. Buses currently will bypass stops that are designated for unbunching by IPT2 (i.e. terminus but not necessarily seen by the game as the first stop of the route).
2. Buses will NOT bypass "first" stop of route* that is NOT designated for unbunching by IPT2
*When a route is drawn, the first click may not necessarily be the first route of the route, but the game "sees" it so.

Perhaps this will just be an additional logic check before the decision to bypass a stop or not is made.

Thank you very much, Sir.

**Comment by Vectorial1024** [comment]
Thanks for the report!

I think I know what happened, something related to how the base mod determines whether to instantly depart, but I will need to think about how to rewrite things. When I figure it out, I may tranfer this issue to the main repo (or not).

Right now I am thinking about this, and no action will be taken yet.

**Comment by Vectorial1024** [comment]
Anyway, more info on the other side https://github.com/Vectorial1024/ExpressBusServices/issues/14

**Comment by Vectorial1024** [comment]
This has been fixed at Steam. The whole set of EBS mods have been updated together to make it work.

Closing this.
